### ISSUE TITLE
PR 생성 시 Reviewers, Assignees, Labels 설정 관련 권한

### ISSUE THREAD

**Issue by seungyeoniii** [drum-grammer/docker-pro-2312#157]
톱니바퀴 설정 버튼이 보이지 않습니다. 권한요청드립니다.
seungyeoniii
입니다.

**Comment by drum-grammer** [comment]
권한 부여를 위해 collaborator 로 초대 드렸습니다. 초대 수락하시면 권한 부여가 완료됩니다.
