### ISSUE TITLE
 PR 등록 관련 권한 요청

### ISSUE THREAD

**Issue by www-author** [drum-grammer/docker-pro-2312#170]
안녕하세요, 
 PR 화면 우측의 Reviewers, Assignees, Labels 설정을 위한 톱니바퀴 설정 버튼이 보이지 않습니다. 권한요청드립니다.
www-author 입니다.

**Comment by drum-grammer** [comment]
collaborator 로 초대 드렸습니다. 초대 수락 하시면 권한 부여가 완료됩니다.
